name: doctor_booking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hive_ce: ^2.12.0
  hive_ce_flutter: ^2.3.2

dev_dependencies:
  build_runner: ^2.8.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.5
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
