// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:doctor_booking/core/database/tables/booking_table.dart';
import 'package:doctor_booking/core/database/tables/doctor_table.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BookingTableAdapter());
    registerAdapter(BookingTableStatusAdapter());
    registerAdapter(DoctorAvailabilityTableAdapter());
    registerAdapter(DoctorSlotTableAdapter());
    registerAdapter(DoctorTableAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BookingTableAdapter());
    registerAdapter(BookingTableStatusAdapter());
    registerAdapter(DoctorAvailabilityTableAdapter());
    registerAdapter(DoctorSlotTableAdapter());
    registerAdapter(DoctorTableAdapter());
  }
}
